// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
// const awsmobile = {
//   aws_app_analytics: 'enable',
//   aws_cognito_identity_pool_id: 'us-east-1:23aa7f6b-48d9-45d1-8f06-8d5e9cc1ed04',
//   aws_cognito_region: 'us-east-1',
//   aws_content_delivery: 'enable',
//   aws_content_delivery_bucket: 'tronwallet-hosting-mobilehub-610187546',
//   aws_content_delivery_bucket_region: 'us-east-1',
//   aws_content_delivery_cloudfront: 'enable',
//   aws_content_delivery_cloudfront_domain: 'd1lzt070f86yrq.cloudfront.net',
//   aws_mobile_analytics_app_id: 'fba1fe8b67264f0a9d1b352bfa6d1458',
//   aws_mobile_analytics_app_region: 'us-east-1',
//   aws_project_id: '64338572-1d0d-406a-bd6d-ccbabaaa0c14',
//   aws_project_name: 'TronWallet',
//   aws_project_region: 'us-east-1',
//   aws_resource_name_prefix: 'tronwallet-mobilehub-610187546',
//   aws_sign_in_enabled: 'enable',
//   aws_user_pools: 'enable',
//   aws_user_pools_id: 'us-east-1_N3aUlhya7',
//   aws_user_pools_mfa_type: 'ON',
//   aws_user_pools_web_client_id: '7qqarntr6cp8f1450ksfvb2ms5',
// };

const awsmobile = {
  aws_project_name: 'TronWallet',
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:c5a0a18d-8fe2-421b-858d-e6a2c7f97f0a',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_i3fDuXSwH',
  aws_user_pools_web_client_id: '3rj2t1v5d9cj2jlrk9u6sq4i2s',
};

export default awsmobile;